baseURL = "http://example.org/"
languageCode = "en-us"
title = "Si Ya's Blog"

theme = "hugo-theme-cleanwhite"

# Define the number of posts per page
paginate = 10


[params]
  header_image = "img/home-bg-jeep.jpg"

  SEOTitle = "Si Ya's Blog"
  slogan = "路在脚下，心向远方"
  description = "赵化冰，程序员, 开源爱好者，生活探险家 | 这里是 赵化冰 的博客，与你一起发现更大的世界。"
  image_404 = "img/404-bg.jpg"
  title_404 = "404 page unfound"


    author = "Si Ya"

    defaultKeywords = ["SiYa", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"
    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."

  featured_tags = true 
  featured_condition_size = 2 

